services:
  backend:
    build: ./backend
    container_name: cti-backend-sqlite
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - ./backend/data:/app/data
  frontend:
    build: ./frontend
    container_name: cti-frontend-vite
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:5000/api
    depends_on:
      - backend
